// Generates config.generated.js from the FITAI_API_URL environment variable.
//
// Used by the Vercel build step so the frontend talks to the deployed backend
// without any manual edits. Set FITAI_API_URL in the Vercel project settings
// (e.g. https://ai-personal-trainer-backend.onrender.com) and redeploy.
const fs = require("fs");
const path = require("path");

function toWsUrl(httpUrl) {
  if (!httpUrl) return "ws://127.0.0.1:8000";
  return httpUrl.replace(/^http:/i, "ws:").replace(/^https:/i, "wss:");
}

const raw = (process.env.FITAI_API_URL || "http://127.0.0.1:8000").trim();
const apiUrl = raw.replace(/\/+$/, "");
const wsUrl = toWsUrl(apiUrl);

if (!process.env.FITAI_API_URL) {
  console.warn(
    "[build] FITAI_API_URL is not set. Falling back to localhost. " +
      "Set FITAI_API_URL in Vercel project env to point at your deployed backend."
  );
}

const content =
  "// AUTO-GENERATED by build.js. Do not edit by hand.\n" +
  "window.FITAI_CONFIG = window.FITAI_CONFIG || {};\n" +
  "window.FITAI_CONFIG.API_BASE = " +
  JSON.stringify(apiUrl) +
  ";\n" +
  "window.FITAI_CONFIG.WS_BASE = " +
  JSON.stringify(wsUrl) +
  ";\n";

const out = path.join(__dirname, "config.generated.js");
fs.writeFileSync(out, content, "utf8");
console.log("[build] wrote " + out + "  API_BASE=" + apiUrl);
